In [21]:
import kagglehub
import pandas as pd
import numpy as np

In [22]:
# Downloading dataset
path = kagglehub.dataset_download("thedevastator/unlock-profits-with-e-commerce-sales-data")

In [23]:
df = pd.read_csv(path+'/Amazon Sale Report.csv', index_col=0)

<ipython-input-23-9fcfdbadf56b>:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path+'/Amazon Sale Report.csv', index_col=0)

In [24]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [25]:
df.shape

(128975, 23)

In [26]:
df.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128975 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  object
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  object
 16  ship-state          128942 non-null  object
 17  ship-postal-code    128942 non-null  float64
 18  ship-country        128942 non-null  object
 19  promotion-ids       79822 non-null   object
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   object
 22  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(1), object(19)
memory usage: 22.8+ MB

In [28]:
# Setting correct data types
df = df.convert_dtypes()

In [29]:
# Set Date column format
df['Date'] = pd.to_datetime(df['Date'], format='%m-%d-%y', dayfirst=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128975 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  string
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  string
 3   Fulfilment          128975 non-null  string
 4   Sales Channel       128975 non-null  string
 5   ship-service-level  128975 non-null  string
 6   Style               128975 non-null  string
 7   SKU                 128975 non-null  string
 8   Category            128975 non-null  string
 9   Size                128975 non-null  string
 10  ASIN                128975 non-null  string
 11  Courier Status      122103 non-null  string
 12  Qty                 128975 non-null  Int64
 13  currency            121180 non-null  string
 14  Amount              121180 non-null  Float64
 15  ship-city           128942 non-null  string
 16  ship-state          128942 non-null  string
 17  ship-postal-code    128942 non-null  Int64
 18  ship-country        128942 non-null  string
 19  promotion-ids       79822 non-null   string
 20  B2B                 128975 non-null  boolean
 21  fulfilled-by        39277 non-null   string
 22  Unnamed: 22         79925 non-null   boolean
dtypes: Float64(1), Int64(2), boolean(2), datetime64[ns](1), string(17)
memory usage: 22.5 MB

In [31]:
# Count of unique values
df.nunique().to_frame(name='Count of unique values')

                    Count of unique values
Order ID                            120378
Date                                    91
Status                                  13
Fulfilment                               2
Sales Channel                            2
ship-service-level                       2
Style                                 1377
SKU                                   7195
Category                                 9
Size                                    11
ASIN                                  7190
Courier Status                           3
Qty                                     10
currency                                 1
Amount                                1410
ship-city                             8955
ship-state                              69
ship-postal-code                      9459
ship-country                             1
promotion-ids                         5787
B2B                                      2
fulfilled-by                             1
Unnamed: 22                              1

In [32]:
# Unique Values
df.apply(pd.unique).to_frame(name='Unique Values')

                                                        Unique Values
Order ID            [405-8078784-5731545, 171-9198151-1101146, 404...
Date                [2022-04-30T00:00:00.000000000, 2022-04-29T00:...
Status              [Cancelled, Shipped - Delivered to Buyer, Ship...
Fulfilment                                         [Merchant, Amazon]
Sales Channel                                 [Amazon.in, Non-Amazon]
ship-service-level                              [Standard, Expedited]
Style               [SET389, JNE3781, JNE3371, J0341, JNE3671, SET...
SKU                 [SET389-KR-NP-S, JNE3781-KR-XXXL, JNE3371-KR-X...
Category            [Set, kurta, Western Dress, Top, Ethnic Dress,...
Size                 [S, 3XL, XL, L, XXL, XS, 6XL, M, 4XL, 5XL, Free]
ASIN                [B09KXVBD7Z, B09K3WFS32, B07WV4JV4D, B099NRCT7...
Courier Status                  [<NA>, Shipped, Cancelled, Unshipped]
Qty                                  [0, 1, 2, 15, 3, 9, 13, 5, 4, 8]
currency                                                  [INR, <NA>]
Amount              [647.62, 406.0, 329.0, 753.33, 574.0, 824.0, 6...
ship-city           [MUMBAI, BENGALURU, NAVI MUMBAI, PUDUCHERRY, C...
ship-state          [MAHARASHTRA, KARNATAKA, PUDUCHERRY, TAMIL NAD...
ship-postal-code    [400081, 560085, 410210, 605008, 600073, 20110...
ship-country                                               [IN, <NA>]
promotion-ids       [<NA>, Amazon PLCC Free-Financing Universal Me...
B2B                                                     [False, True]
fulfilled-by                                        [Easy Ship, <NA>]
Unnamed: 22                                             [<NA>, False]

In [33]:
# Missing Values Count
missing_count = df.isnull().sum()
missing_count[missing_count > 0].to_frame(name='Count of missing values')

                  Count of missing values
Courier Status                       6872
currency                             7795
Amount                               7795
ship-city                              33
ship-state                             33
ship-postal-code                       33
ship-country                           33
promotion-ids                       49153
fulfilled-by                        89698
Unnamed: 22                         49050

In [34]:
# Deriving relation between 'Status' and 'Courier Status' to handle missing values in 'Courier Status'
df[['Status', 'Courier Status']].drop_duplicates()

                               Status Courier Status
index
0                           Cancelled           <NA>
1        Shipped - Delivered to Buyer        Shipped
2                             Shipped        Shipped
8                           Cancelled      Cancelled
116                         Cancelled      Unshipped
244      Shipped - Returned to Seller        Shipped
433       Shipped - Rejected by Buyer        Shipped
937                           Shipped      Unshipped
1615                          Shipped      Cancelled
4017        Shipped - Lost in Transit        Shipped
15631      Shipped - Out for Delivery        Shipped
16633   Shipped - Returning to Seller        Shipped
18894    Shipped - Delivered to Buyer           <NA>
29965             Shipped - Picked Up        Shipped
44043                         Pending      Unshipped
58986                         Pending      Cancelled
58987                         Pending        Shipped
71443    Shipped - Returned to Seller           <NA>
91974   Pending - Waiting for Pick Up      Unshipped
102676              Shipped - Damaged        Shipped
107949                       Shipping      Unshipped

In [35]:
df.replace('<NA>', np.nan, inplace=True)

In [36]:
# Removing columns with too many missing values
columns_to_drop = ['Unnamed: 22', 'fulfilled-by', 'promotion-ids']
df.drop(columns=columns_to_drop, axis=1, inplace=True)

# Removing 'Currency' column due to having only one unique value (INR)
df.drop(['currency'], axis=1, inplace=True)

# Removing rows with missing shipping info due to small amount of them
df.dropna(subset=['ship-city', 'ship-state', 'ship-postal-code', 'ship-country'], inplace=True)

# Filling missing values in 'Amount' with the mean
df['Amount'].fillna(df['Amount'].mean(), inplace=True)  # Fill with mean

# Filling missing values in 'Courier Status' with the most frequent value associated with 'Status' when 'Status' is Cancelled
freq_value = df.loc[df['Status'] == 'Cancelled','Courier Status'].value_counts().idxmax() # Cancelled
df.loc[df['Status'] == 'Cancelled','Courier Status'] = df.loc[df['Status'] == 'Cancelled','Courier Status'].fillna(freq_value)

# Filling missing values in 'Courier Status' with "Shipped" when 'Status' is "Shipped - Returned to Seller" or "Shipped - Delivered to Buyer"
df.loc[(df['Status'] == 'Shipped - Returned to Seller') | (df['Status'] == 'Shipped - Delivered to Buyer'), 'Courier Status'] = df.loc[(df['Status'] == 'Shipped - Returned to Seller') | (df['Status'] == 'Shipped - Delivered to Buyer'), 'Courier Status'].fillna('Shipped')

In [37]:
df_daily = df.groupby('Date')['Amount'].sum().reset_index()

In [38]:
df_daily = df_daily.set_index('Date')

In [39]:
df_daily['day_of_week'] = df_daily.index.dayofweek

In [40]:
df_daily['is_weekend'] = (df_daily['day_of_week'] >= 5).astype(int)

In [41]:
#most important lag features
df_daily['lag_1'] = df_daily['Amount'].shift(1)
df_daily['lag_7'] = df_daily['Amount'].shift(7)  # Weekly seasonality

In [42]:
# Simple moving average
df_daily['rolling_3_mean'] = df_daily['Amount'].rolling(window=3).mean()

In [43]:
df_daily = df_daily.dropna()

In [44]:
# Missing Values Count
missing_count = df.isnull().sum()
missing_count[missing_count > 0].to_frame(name='Count of missing values')

Empty DataFrame
Columns: [Count of missing values]
Index: []

In [45]:
df.to_csv('Cleaned Amazon Sale Report.csv', index=False)

In [46]:
df_daily.to_csv('Amazon Sale Time Series.csv')